name: Day-03-Binary-Diagnostic

on:
  workflow_dispatch:
  push:
    paths:
      - '**Day-03**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: fwal/setup-swift@v1
        with:
            swift-version: "5"
      - uses: actions/checkout@v2
      - name: Run script
        run: |
          xcrun --sdk macosx swiftc -parse-as-library Day-03*.swift InputReader.swift -o ./Day-03
          ./Day-03
