name: Day-17-Trick-Shot

on:
  workflow_dispatch:
  push:
    paths:
      - '**Day-17**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: fwal/setup-swift@v1
        with:
            swift-version: "5"
      - uses: actions/checkout@v2
      - name: Run script
        run: |
          xcrun --sdk macosx swiftc -parse-as-library Day-17*.swift InputReader.swift -o ./Day-17
          ./Day-17
