name: Day-01-LoremIpsum

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: fwal/setup-swift@d43a564349d1341cd990cfbd70d94d63b8899475
        with:
            swift-version: "5.5"
      - uses: actions/checkout@v2
      - name: Get swift version
        run: swift --version
