name: Day-02-Dive!

on:
  workflow_dispatch:
  push:
    paths:
      - '**Day-02**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: fwal/setup-swift@v1
        with:
            swift-version: "5"
      - uses: actions/checkout@v2
      - name: Run script
        run: |
          xcrun --sdk macosx swiftc -parse-as-library Day-02*.swift InputReader.swift -o ./Day-02
          ./Day-02
