name: Day-09-Smoke-Basin

on:
  workflow_dispatch:
  push:
    paths:
      - '**Day-09**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: fwal/setup-swift@v1
        with:
            swift-version: "5"
      - uses: actions/checkout@v2
      - name: Run script
        run: |
          xcrun --sdk macosx swiftc -parse-as-library Day-09*.swift InputReader.swift -o ./Day-09
          ./Day-09
